CREATE TABLE tb_best_car.ctlg_paises_iso (
	id_codigo_iso char(3) null PRIMARY KEY,  --- llave primaria 
	nombre_pais varchar(100) NULL
);



INSERT INTO tb_best_car.ctlg_paises_iso (codigo_iso_alfa3, nombre_pais) VALUES
('AFG', 'Afganistán'),
('ALB', 'Albania'),
('DZA', 'Argelia'),
('AND', 'Andorra'),
('AGO', 'Angola'),
('ARG', 'Argentina'),
('ARM', 'Armenia'),
('AUS', 'Australia'),
('AUT', 'Austria'),
('AZE', 'Azerbaiyán'),
('BHS', 'Bahamas'),
('BHR', 'Baréin'),
('BGD', 'Bangladés'),
('BRB', 'Barbados'),
('BLR', 'Bielorrusia'),
('BEL', 'Bélgica'),
('BLZ', 'Belice'),
('BEN', 'Benín'),
('BTN', 'Bután'),
('BOL', 'Bolivia'),
('BIH', 'Bosnia y Herzegovina'),
('BWA', 'Botsuana'),
('BRA', 'Brasil'),
('BRN', 'Brunéi'),
('BGR', 'Bulgaria'),
('BFA', 'Burkina Faso'),
('BDI', 'Burundi'),
('KHM', 'Camboya'),
('CMR', 'Camerún'),
('CAN', 'Canadá'),
('CPV', 'Cabo Verde'),
('CAF', 'República Centroafricana'),
('TCD', 'Chad'),
('CHL', 'Chile'),
('CHN', 'China'),
('COL', 'Colombia'),
('COM', 'Comoras'),
('COG', 'Congo'),
('CRI', 'Costa Rica'),
('HRV', 'Croacia'),
('CUB', 'Cuba'),
('CYP', 'Chipre'),
('CZE', 'Chequia'),
('DNK', 'Dinamarca'),
('DJI', 'Yibuti'),
('DMA', 'Dominica'),
('DOM', 'República Dominicana'),
('ECU', 'Ecuador'),
('EGY', 'Egipto'),
('SLV', 'El Salvador'),
('GNQ', 'Guinea Ecuatorial'),
('ERI', 'Eritrea'),
('EST', 'Estonia'),
('SWZ', 'Esuatini'),
('ETH', 'Etiopía'),
('FJI', 'Fiyi'),
('FIN', 'Finlandia'),
('FRA', 'Francia'),
('GAB', 'Gabón'),
('GMB', 'Gambia'),
('GEO', 'Georgia'),
('DEU', 'Alemania'),
('GHA', 'Ghana'),
('GRC', 'Grecia'),
('GRD', 'Granada'),
('GTM', 'Guatemala'),
('GIN', 'Guinea'),
('GNB', 'Guinea-Bisáu'),
('GUY', 'Guyana'),
('HTI', 'Haití'),
('HND', 'Honduras'),
('HUN', 'Hungría'),
('ISL', 'Islandia'),
('IND', 'India'),
('IDN', 'Indonesia'),
('IRN', 'Irán'),
('IRQ', 'Irak'),
('IRL', 'Irlanda'),
('ISR', 'Israel'),
('ITA', 'Italia'),
('JAM', 'Jamaica'),
('JPN', 'Japón'),
('JOR', 'Jordania'),
('KAZ', 'Kazajistán'),
('KEN', 'Kenia'),
('KIR', 'Kiribati'),
('PRK', 'Corea del Norte'),
('KOR', 'Corea del Sur'),
('KWT', 'Kuwait'),
('KGZ', 'Kirguistán'),
('LAO', 'Laos'),
('LVA', 'Letonia'),
('LBN', 'Líbano'),
('LSO', 'Lesoto'),
('LBR', 'Liberia'),
('LBY', 'Libia'),
('LIE', 'Liechtenstein'),
('LTU', 'Lituania'),
('LUX', 'Luxemburgo'),
('MDG', 'Madagascar'),
('MWI', 'Malaui'),
('MYS', 'Malasia'),
('MDV', 'Maldivas'),
('MLI', 'Malí'),
('MLT', 'Malta'),
('MHL', 'Islas Marshall'),
('MRT', 'Mauritania'),
('MUS', 'Mauricio'),
('MEX', 'México'),
('FSM', 'Micronesia'),
('MDA', 'Moldavia'),
('MCO', 'Mónaco'),
('MNG', 'Mongolia'),
('MNE', 'Montenegro'),
('MAR', 'Marruecos'),
('MOZ', 'Mozambique'),
('MMR', 'Birmania'),
('NAM', 'Namibia'),
('NRU', 'Nauru'),
('NPL', 'Nepal'),
('NLD', 'Países Bajos'),
('NZL', 'Nueva Zelanda'),
('NIC', 'Nicaragua'),
('NER', 'Níger'),
('NGA', 'Nigeria'),
('MKD', 'Macedonia del Norte'),
('NOR', 'Noruega'),
('OMN', 'Omán'),
('PAK', 'Pakistán'),
('PLW', 'Palaos'),
('PAN', 'Panamá'),
('PNG', 'Papúa Nueva Guinea'),
('PRY', 'Paraguay'),
('PER', 'Perú'),
('PHL', 'Filipinas'),
('POL', 'Polonia'),
('PRT', 'Portugal'),
('QAT', 'Catar'),
('ROU', 'Rumanía'),
('RUS', 'Rusia'),
('RWA', 'Ruanda'),
('KNA', 'San Cristóbal y Nieves'),
('LCA', 'Santa Lucía'),
('VCT', 'San Vicente y las Granadinas'),
('WSM', 'Samoa'),
('SMR', 'San Marino'),
('STP', 'Santo Tomé y Príncipe'),
('SAU', 'Arabia Saudita'),
('SEN', 'Senegal'),
('SRB', 'Serbia'),
('SYC', 'Seychelles'),
('SLE', 'Sierra Leona'),
('SGP', 'Singapur'),
('SVK', 'Eslovaquia'),
('SVN', 'Eslovenia'),
('SLB', 'Islas Salomón'),
('SOM', 'Somalia'),
('ZAF', 'Sudáfrica'),
('SSD', 'Sudán del Sur'),
('ESP', 'España'),
('LKA', 'Sri Lanka'),
('SDN', 'Sudán'),
('SUR', 'Surinam'),
('SWE', 'Suecia'),
('CHE', 'Suiza'),
('SYR', 'Siria'),
('TWN', 'Taiwán'),
('TJK', 'Tayikistán'),
('TZA', 'Tanzania'),
('THA', 'Tailandia'),
('TLS', 'Timor Oriental'),
('TGO', 'Togo'),
('TON', 'Tonga'),
('TTO', 'Trinidad y Tobago'),
('TUN', 'Túnez'),
('TUR', 'Turquía'),
('TKM', 'Turkmenistán'),
('TUV', 'Tuvalu'),
('UGA', 'Uganda'),
('UKR', 'Ucrania'),
('ARE', 'Emiratos Árabes Unidos'),
('GBR', 'Reino Unido'),
('USA', 'Estados Unidos'),
('URY', 'Uruguay'),
('UZB', 'Uzbekistán'),
('VUT', 'Vanuatu'),
('VAT', 'Ciudad del Vaticano'),
('VEN', 'Venezuela'),
('VNM', 'Vietnam'),
('YEM', 'Yemen'),
('ZMB', 'Zambia'),
('ZWE', 'Zimbabue');


select * from tb_best_car.ctlg_paises_iso
